#ifndef _XPARAMETERS_H_
#define _XPARAMETERS_H_

#define INTC_DEVICE_ID 0
#define CORDIC_DEVICE_ID 0

#define XIL_EXCEPTION_ID_IRQ_INT 0

#define XPAR_PS7_SCUGIC_0_DEVICE_ID 0
#define XPAR_XSCUGIC_NUM_INSTANCES 1

#define XPAR_CORDIC_CC_TOP_0_DEVICE_ID 0
#define XPAR_XCORDIC_CC_NUM_INSTANCES 1
#define XPAR_CORDIC_CC_TOP_0_S_AXI_CORDIC_IF_BASEADDR 0x00004711

#define XST_SUCCESS 0
#define XST_FAILURE -1
#define XST_DEVICE_NOT_FOUND -2

#endif /* _XPARAMETERS_H_ */
